# Початок роботи з таблицями

In [1]:
from datascience import *
path_data = '../../../assets/data/'
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

cones = Table.read_table(path_data + 'cones.csv')
nba = Table.read_table(path_data + 'nba_salaries.csv').relabeled(3, 'SALARY')
movies = Table.read_table(path_data + 'movies_by_year.csv')

Тепер ми можемо використовувати Python для аналізу даних. Ми будемо працювати з даними, що зберігаються у структурах таблиць.

Таблиці — це основний спосіб представлення наборів даних. Таблицю можна розглядати у двох напрямках:
* як послідовність іменованих стовпців, кожен з яких описує окрему характеристику всіх рядків у наборі даних, або
* як послідовність рядків, кожен з яких містить всю інформацію про окремого суб’єкта в наборі даних.

Ми детально вивчатимемо таблиці в наступних кількох розділах. А поки що ми лише ознайомимося з кількома методами, не заглиблюючись у технічні подробиці.

Таблиця `cones` вже імпортована для нас; пізніше ми побачимо, як саме, а тут просто попрацюємо з нею. Спочатку давайте поглянемо на неї.

In [2]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

Таблиця має шість рядків. Кожен рядок відповідає одному ріжку морозива. Ріжки морозива — це *індивідууми*.

Кожен ріжок має три атрибути: смак, колір і ціну. Кожен стовпець містить дані про один із цих атрибутів, тому всі записи в будь-якому стовпці є одного типу. Кожен стовпець має назву. Ми будемо посилатися на стовпці за їхніми назвами.

Метод (method) таблиці схожий на функцію, але він повинен оперувати таблицею. Тому виклик має вигляд

`назва_таблиці.метод(аргументи)`
`name_of_table.method(arguments)`

Наприклад, якщо ви хочете переглянути лише перші два рядки таблиці, ви можете використати метод таблиці `show`.

In [3]:
cones.show(2)

Ви можете замінити 2 на будь-яку кількість рядків. Якщо ви запитаєте більше шести, ви отримаєте лише шість, оскільки `cones` має лише шість рядків.

## Вибір групи стовпців
Метод `select` створює нову таблицю, що складається виключно із зазначених стовпців.

In [4]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

При цьому вихідна таблиця залишається без змін.

In [5]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

Ви можете вибрати кілька стовпців, розділивши їхні назви комами.

In [6]:
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

Ви також можете *видалити* (*drop*) непотрібні стовпці. Наведену вище таблицю можна створити, видаливши стовпець `Color`.

In [7]:
cones.drop('Color')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

Ви можете надати цій новій таблиці ім’я та переглянути її ще раз, просто ввівши її ім’я.

In [8]:
no_colors = cones.drop('Color')

no_colors

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

Як і `select`, метод `drop` створює меншу таблицю, залишаючи вихідну таблицю без змін. Щоб дослідити ваші дані, ви можете створювати будь-яку кількість менших таблиць, додаючи або видаляючи стовпці. Це ніяк не зашкодить вашій вихідній таблиці даних.

## Сортування рядків

Метод `sort` створює нову таблицю, упорядковуючи рядки вихідної таблиці у порядку зростання (ascending) значень у вказаному стовпці. У цьому прикладі таблиця `cones` відсортована за ціною рожків у порядку зростання.

In [9]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

Щоб відсортувати в порядку зменшення (descending), можна використати *опціональний* (*optional*) аргумент функції `sort`. Як випливає з назви, опціональні аргументи не є обов’язковими, але їх можна використовувати, якщо потрібно змінити поведінку методу за замовчуванням.

За замовчуванням функція `sort` сортує за зростанням значень у вказаному стовпці. Щоб відсортувати в порядку зменшення, використовуйте опціональний аргумент `descending=True`.

In [10]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75
chocolate  | light brown | 4.75
strawberry | pink        | 3.55

Як і `select` та `drop`, метод `sort` не змінює вихідну таблицю.

## Вибір рядків, що відповідають умові
Метод `where` створює нову таблицю, що складається виключно з рядків, які відповідають заданій умові. У цьому розділі ми будемо працювати з дуже простою умовою: значення у вказаному стовпці має дорівнювати значенню, яке ми також вказуємо. Отже, метод `where` має два аргументи.

In [11]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

Аргументи, розділені комою, — це назва стовпця та значення, яке ми шукаємо в цьому стовпці. Метод `where` також можна використовувати, коли умова, якій повинні відповідати рядки, є складнішою. У таких випадках виклик методу також буде дещо складнішим.

Важливо вказати значення точно. Наприклад, якщо ми вкажемо `Chocolate` замість `chocolate`, то `where` правильно не знайде жодного рядка, де смак — `Chocolate`.

In [12]:
cones.where('Flavor', 'Chocolate')

Flavor | Color | Price

Як і всі інші табличні методи в цьому розділі, `where` залишає вихідну таблицю без змін.

## Приклад: зарплати в НБА

«NBA є найбільш високооплачуваною професійною спортивною лігою у світі», [повідомляло CNN](http://edition.cnn.com/2015/12/04/sport/gallery/highest-paid-nba-players/) у березні 2016 року. Таблиця «nba» містить [зарплати всіх Національних баскетбольних асоціацій гравців](https://www.statcrunch.com/app/index.php?dataid=1843341) у 2015-2016 рр.

Кожен рядок представляє одного гравця. Стовпці:
| **Мітка стовпця** | опис                                    |
|--------------------|-----------------------------------------------------|
| `PLAYER`           | Ім'я гравця                                       |
| `POSITION`         | Позиція гравця в команді                        |
| `TEAM`             | Назва команди                                       |
|`SALARY`    | Зарплата гравця в 2015-2016 роках, мільйони доларів|
 
Код позиції такий PG (Розігруючий захисник Point Guard), SG (Атакуючий захисник Shooting Guard), PF (Силовий форвард Power Forward), SF (малий форвард Small Forward), and C (Центровий Center). Однак у подальшому тексті не йдеться про те, як саме грають у баскетбол.

У першому рядку вказано, що Пол Міллсап, сильний форвард команди «Атланта Хокс», у сезоні 2015–2016 отримав зарплату в розмірі майже $\$18,7$ мільйонів.

In [13]:
nba

PLAYER           | POSITION | TEAM          | SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

Шанувальники Стівена Каррі можуть знайти його рядок за допомогою `where`.

In [14]:
nba.where('PLAYER', 'Stephen Curry')

PLAYER        | POSITION | TEAM                  | SALARY
Stephen Curry | PG       | Golden State Warriors | 11.3708

Ми також можемо створити нову таблицю під назвою `warriors`, яка міститиме лише дані про команду «Голден Стейт Ворріорс».

In [15]:
warriors = nba.where('TEAM', 'Golden State Warriors')
warriors

PLAYER            | POSITION | TEAM                  | SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

За замовчуванням відображаються перші 10 рядків таблиці. Ви можете скористатися командою `show`, щоб відобразити більше або менше рядків. Щоб відобразити всю таблицю, скористайтеся командою `show` без аргументів у дужках.

In [16]:
warriors.show()

Таблиця `nba` відсортована за алфавітом за назвами команд. Щоб побачити, скільки заробляли гравці у сезоні 2015–2016 років, доцільно відсортувати дані за розміром зарплати. Пам’ятайте, що за замовчуванням сортування здійснюється у порядку зростання.

In [17]:
nba.sort('SALARY')

PLAYER                 | POSITION | TEAM                 | SALARY
Thanasis Antetokounmpo | SF       | New York Knicks      | 0.030888
Jordan McRae           | SG       | Phoenix Suns         | 0.049709
Cory Jefferson         | PF       | Phoenix Suns         | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies    | 0.055722
Orlando Johnson        | SG       | Phoenix Suns         | 0.055722
Phil Pressey           | PG       | Phoenix Suns         | 0.055722
Keith Appling          | PG       | Orlando Magic        | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets       | 0.099418
Erick Green            | PG       | Utah Jazz            | 0.099418
Jeff Ayres             | PF       | Los Angeles Clippers | 0.111444
... (407 rows omitted)

Ці цифри дещо складно порівнювати, оскільки деякі з цих гравців протягом сезону змінювали команди й отримували зарплату від більш ніж однієї команди; у таблиці вказано лише зарплату від останньої команди.

Репортаж CNN присвячений протилежному кінцю шкали зарплат — гравцям, які входили до числа найбільш високооплачуваних у світі. Щоб визначити цих гравців, можна відсортувати список за зарплатою у спадному порядку (descending order) й розглянути кілька верхніх рядків.

In [18]:
nba.sort('SALARY', descending=True)

PLAYER          | POSITION | TEAM                  | SALARY
Kobe Bryant     | SF       | Los Angeles Lakers    | 25
Joe Johnson     | SF       | Brooklyn Nets         | 24.8949
LeBron James    | SF       | Cleveland Cavaliers   | 22.9705
Carmelo Anthony | SF       | New York Knicks       | 22.875
Dwight Howard   | C        | Houston Rockets       | 22.3594
Chris Bosh      | PF       | Miami Heat            | 22.1927
Chris Paul      | PG       | Los Angeles Clippers  | 21.4687
Kevin Durant    | SF       | Oklahoma City Thunder | 20.1586
Derrick Rose    | PG       | Chicago Bulls         | 20.0931
Dwyane Wade     | SG       | Miami Heat            | 20
... (407 rows omitted)

Покійний Кобі Брайант був найвисокооплачуваним гравцем НБА у сезоні 2015–2016 років.